name: CI
on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2.0.0
      - run: cargo check
      - run: cargo fmt --all --check
      - run: cargo clippy --all-features -- -D warnings
      - run: cargo build --release --all-features

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Set grcov version
        run: echo "GRCOV_VERSION=$(cargo search --limit 1 grcov | head -n1 | cut -d '"' -f2)" >> $GITHUB_ENV
      - run: cargo install --version $GRCOV_VERSION grcov
      - name: Clean coverage
        run: |
          rm -f target/debug/deps/*.gcda
          rm -f target/debug/deps/*.gcno
      - uses: Swatinem/rust-cache@v2.0.0
        with:
          key: ${{ env.GRCOV_VERSION }}
      - run: cargo test --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: |
            -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off
          RUSTDOCFLAGS: |
            -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off
      - uses: actions-rs/grcov@v0.1
      - uses: codecov/codecov-action@v3
        with:
          file: ./lcov.info

  cargo-sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2.0.0
      - run: cargo install cargo-sort
      - run: cargo-sort --check

  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lycheeverse/lychee-action@v1.5.1
        with:
          args: . --verbose --exclude "pkg_name|your_own_registry"
          fail: true

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dprint/check@v2.1
