name: Linters
on: pull_request

jobs:
  misspell:
    name: linters / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-misspell@v1
        with:
          locale: "US"

  commitlint:
    name: linters / commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4.1.9
